[package]
name = "blade-ink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "bladeink"
path = "src/lib.rs"

[[bin]]
name = "console-player"
path = "src/bin/console-player.rs"

[dependencies]
