[package]
name = "bladeink"
version.workspace = true
authors.workspace = true
description = """
This is a Rust port of inkle's ink, a scripting language for writing interactive narrative.
"""
license.workspace = true
repository.workspace = true
keywords = ["ink", "gamedev", "narrative"]
categories = ["game-development"]
readme = "../README.md"
edition.workspace = true

[lib]
name = "bladeink"
path = "src/lib.rs"

[dependencies]
serde_json = { workspace = true, optional = true }
strum = { version = "0.28", default-features = false, features = ["derive"] }
as-any = "0.3.0"
rand = { workspace = true, features = ["std_rng"] }
web-time = { version = "1.1.0", optional = true }
hashbrown = "0.16"
libm = "0.2"
core3 = { version = "0.1", default-features = false, features = ["alloc"] }

[features]
default = ["std", "serde-json-parser"]
std = ["dep:web-time", "dep:getrandom", "core3/std", "rand/thread_rng"]
serde-json-parser = ["dep:serde_json"]
stream-json-parser = []

[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dependencies]
getrandom = { version = "0.4", features = ["wasm_js"], optional = true }
