//! A generated [`Choice`] from the story.
use crate::compat::cell::RefCell;
#[allow(unused_imports)]
use crate::prelude::*;
use core::fmt;

use crate::{
    object::{Object, RTObject},
    path::Path,
};

/// Represents a choice generated by a [`Story`](crate::story::Story).
#[derive(Clone)]
pub struct Choice {
    obj: Object,
    pub(crate) original_thread_index: RefCell<usize>,
    /// Get the path to the original choice point - where was this choice defined in the story?
    pub(crate) source_path: String,
    pub(crate) target_path: Path,
    /// Ink tags attached to this `Choice`.
    pub tags: Vec<String>,
    /// The original index into `currentChoices` list on the [`Story`](crate::story::Story) when
    /// this `Choice` was generated, for convenience.
    pub index: RefCell<usize>,
    /// The main text to present to the player for this `Choice`.
    pub text: String,
}

impl Choice {
    pub(crate) fn new_from_json(
        path_string_on_choice: &str,
        source_path: String,
        text: &str,
        index: usize,
        original_thread_index: usize,
        choice_tags: Vec<String>,
    ) -> Choice {
        Choice {
            obj: Object::new(),
            target_path: Path::new_with_components_string(Some(path_string_on_choice)),
            tags: choice_tags,
            index: RefCell::new(index),
            original_thread_index: RefCell::new(original_thread_index),
            text: text.to_string(),
            source_path,
        }
    }
}

impl RTObject for Choice {
    fn get_object(&self) -> &Object {
        &self.obj
    }
}

impl fmt::Display for Choice {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "**Choice**")
    }
}
