pub trait ErrorHandler {
    fn error(message: &str, error_type: ErrorType);
}

pub enum ErrorType {
        // Generated by a "TODO" note in the ink source
        Author,
        // You should probably fix this, but it's not critical
        Warning,
        // Critical error that can't be recovered from
        Error
}