name: Rust CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Build
      run: cargo build

    - name: Check fmt
      run: cargo fmt -- --check

    - name: Check Clippy
      run: cargo clippy -- -D warnings

    - name: Test
      run: |
        cargo test
        cargo test -p bladeink --features stream-json-parser
