name: Rust CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: "1.95"
        components: rustfmt, clippy
        targets: thumbv7em-none-eabihf

    - name: Build
      run: cargo build

    - name: Check fmt
      run: cargo fmt -- --check

    - name: Check Clippy
      run: |
        cargo clippy --workspace --all-targets --all-features -- -D warnings
        cargo clippy -p bladeink --lib --no-default-features --features stream-json-parser -- -D warnings

    - name: Check no_std target
      run: cargo check -p bladeink --lib --no-default-features --features stream-json-parser --target thumbv7em-none-eabihf

    - name: Test
      run: |
        cargo test
        cargo test -p bladeink --features stream-json-parser
        cargo test -p bladeink --no-default-features --features stream-json-parser
        cargo test -p conformance-tests --features bladeink/stream-json-parser
