name: Upload Rust Packages

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  check:
    name: Quality gate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: Check fmt
      run: cargo fmt -- --check
    - name: Check Clippy
      run: cargo clippy -- -D warnings
    - name: Test
      run: |
        cargo test
        cargo test -p bladeink --features stream-json-parser

  upload-rinklecate:
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows, macos]
        include:
        - build: linux
          os: ubuntu-latest
          exec: rinklecate
          platform: x86_64-linux
        - build: macos
          os: macos-latest
          exec: rinklecate
          platform: x86_64-macos
        - build: windows
          os: windows-latest
          exec: rinklecate.exe
          platform: x86_64-windows
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build package
      run: |
        cargo build --release
    - name: Upload rinklecate to Github release
      run: |
        staging="rinklecate-${{github.event.release.tag_name}}-${{ matrix.platform }}"
        mkdir "$staging"
        cp target/release/${{ matrix.exec }} "$staging/"

        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          7z a "$staging.zip" "$staging"
          gh release upload ${{github.event.release.tag_name}} "$staging.zip"
        else
          tar czf "$staging.tar.gz" "$staging"
          gh release upload ${{github.event.release.tag_name}} "$staging.tar.gz"
        fi
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      shell: bash

  publish:
    name: Publish packages in crates.io
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Publish
      run: |
        cargo publish -p bladeink --token ${CRATES_TOKEN}
        cargo publish -p bladeink-compiler --token ${CRATES_TOKEN}
        cargo publish -p rinklecate --token ${CRATES_TOKEN}
      env:
        CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
